#!/bin/bash

# Parsing cmdline opts in bash scripts
# http://www.bahmanm.com/blogs/command-line-options-how-to-parse-in-bash-using-getopt
DIRFLAG="-d"
if [ $1 != $DIRFLAG ]; then
    echo usage: moss -d \<lab_directory\>
    exit
fi
if [ -z "$2" ]; then
    echo usage: moss -d \<lab_directory\>
    exit
fi
DIR=$2 
RESULTS=$(./moss -l mips ./$DIR/*.s | grep '^http')
echo $RESULTS
curl -o "./$DIR/results.html" -L $RESULTS

# ./moss -l mips ./$DIR/*.s | grep '^http' > $OUTPUTDIR
# ./moss -l mips ./simple/*.s | grep '^http' > output.txt
