#!/bin/bash

# Parsing cmdline opts in bash scripts
# http://www.bahmanm.com/blogs/command-line-options-how-to-parse-in-bash-using-getopt
FLAG="-d"
if [ $1 != $FLAG ]; then
    echo usage: moss -d \<lab_directory\>
    exit
fi
if [ -z "$2" ]; then
    echo usage: moss -d \<lab_directory\>
    exit
fi
DIR=$2
OUTPUTDIR="./$DIR/output.txt" 
./moss -l mips ./$DIR/*.s | grep '^http' > $OUTPUTDIR
# ./moss -l mips ./simple/*.s | grep '^http' > output.txt
